### ISSUE TITLE
Issue with Appium set up

### ISSUE THREAD

**Issue by pujarijdevan** [mosclofri/cucumber-ui-automation-test#1]
java.lang.ExceptionInInitializerError
	at com.appium.framework.core.AppiumCukes.startAppium(AppiumCukes.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: io.appium.java_client.service.local.InvalidNodeJSInstance: Node.js is not installed!
	at io.appium.java_client.service.local.AppiumServiceBuilder.findDefaultExecutable(AppiumServiceBuilder.java:196)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:329)
	at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:76)
	at com.appium.framework.core.AppiumServer.<clinit>(AppiumServer.java:21)
	... 16 more
Caused by: java.lang.NullPointerException: Unable to find executable for: node.exe
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:883)
	at org.openqa.selenium.os.UnixProcess.<init>(UnixProcess.java:65)
	at org.openqa.selenium.os.CommandLine.<init>(CommandLine.java:38)
	at io.appium.java_client.service.local.AppiumServiceBuilder.findDefaultExecutable(AppiumServiceBuilder.java:190)
	... 19 more

**Comment by pujarijdevan** [comment]
Woked well when installed via npm install appium
